[phases.setup]
nixPkgs = [
    "php83",
    "php83.extensions.curl",
    "php83.extensions.gd", 
    "php83.extensions.openssl",
    "php83.extensions.mbstring",
    "php83.extensions.pdo_pgsql",
    "php83.extensions.bcmath",
    "php83.extensions.xml",
    "php83.extensions.zip",
    "php83.extensions.sodium"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[phases.start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"